server:
  undertow:
    direct-buffers: true
    buffer-size: 16364
    threads:
      io: 16
      worker: 128
    max-http-post-size: -1B
    eager-filter-init: true
    max-parameters: 1000
    max-headers: 200
    max-cookies: 200
    allow-encoded-slash: false
    decode-url: true
    url-charset: utf-8
    always-set-keep-alive: true
    no-request-timeout: -1
    preserve-path-on-forward: false
    options:
      socket:
        SSL_ENABLED: false
      server:
        ALLOW_UNKNOWN_PROTOCOLS: false
        RECORD_REQUEST_START_TIME: true
    # 开启access日志
    accesslog:
      dir: logs
      enabled: true
      pattern: '{
                  "transportProtocol":"%{TRANSPORT_PROTOCOL}",
                  "scheme":"%{SCHEME}",
                  "protocol":"%{PROTOCOL}",
                  "method":"%{METHOD}",
                  "reqHeaderUserAgent":"%{i,User-Agent}",
                  "cookieUserId": "%{c,userId}",
                  "queryTest": "%{q,test}",
                  "queryString": "%q",
                  "relativePath": "%R, %{REQUEST_PATH}, %{RESOLVED_PATH}",
                  "requestLine": "%r",
                  "uri": "%U",
                  "thread": "%I",
                  "hostPort": "%{HOST_AND_PORT}",
                  "localIp": "%A",
                  "localPort": "%p",
                  "localServerName": "%v",
                  "remoteIp": "%a",
                  "remoteHost": "%h",
                  "bytesSent": "%b",
                  "time":"%{time,yyyy-MM-dd HH:mm:ss.S}",
                  "status":"%s",
                  "reason":"%{RESPONSE_REASON_PHRASE}",
                  "respHeaderUserSession":"%{o,userSession}",
                  "respCookieUserId":"%{resp-cookie,userId}",
                  "timeUsed":"%Dms",
                }'
      rotate: true
      suffix: .log
      prefix: access_log