server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.153:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.5.153:8848
        username: nacos
        password: nacos
    gateway:
      routes: #配置路由规则
        - id: arthur-api-route
          uri: lb://arthur-admin
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: arthur-auth-route
          uri: lb://arthur-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:18711/rsa/publicKey' #配置RSA的公钥访问地址

  application:
    name: arthur-admin-gateway
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    port: 6379
    host: 192.168.5.153
    password: 123456

secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"

