spring:
  application:
    name: arthur-uaa
  profiles:
    group:
      prod: log, actuator, undertow, sentinel, redis
    active: prod
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 192.168.5.153:8848
      discovery:
        instance-enabled: false
        failure-tolerance-enabled: true
    openfeign:
      httpclient:
        enabled: true
        max-connections: 200
        max-connections-per-route: 50
  lifecycle:
    timeout-per-shutdown-phase: 20s
  mvc:
    servlet:
      load-on-startup: 1
server:
  shutdown: GRACEFUL
  port: 9090