spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.153:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.5.153:8848
        username: nacos
        password: nacos